---
title: "Running a simple simulation"
description: "Get Started with MSTWeatherGen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{Running a simple simulation}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options:
    chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```


```{r}
library(MSTWeatherGen)
```

```{r}
names = c("Wind","Temp_max","Precipitation")

data(real_data, package = "MSTWeatherGen")
data(coordinates, package = "MSTWeatherGen")
#load("/home/sobakrim/Bureau/MSTWeatherGen/MSTWeatherGen/data/data.rda")
#load("/home/sobakrim/Bureau/MSTWeatherGen/MSTWeatherGen/data/coordinates.rda")
dates = seq(as.Date("2017-01-01"),as.Date("2021-12-31"), by="day")
names_weather_types = c("Wind", "Temp_max")
seasons <- list(
  s1 = list(min_day = 1, max_day = 29, min_month = 12, max_month = 2),
  s2 = list(min_day = 1, max_day = 31, min_month = 3, max_month = 5),
  s3 = list(min_day = 1, max_day = 31, min_month = 6, max_month = 8),
  s4 = list(min_day = 1, max_day = 30, min_month = 9, max_month = 11)
)
names_seasons = c("DJF", "MAM", "JJA", "SON")

```


```{r}
real_data = data_compression(real_data)
```


```{r}

swg = MSTSWG_estimation(data = data, seasons = seasons,dates = dates, names = names, by_season = T,
                                 names_weather_types = names_weather_types,coordinates= coordinates, 
                                 max_it=100, tmax=2, n1=10, n2=10)
```

```{r}
AR_lag = 2
bk = calculate_AR_coefficients_matrices(parm = swg, coordinates = coordinates, AR_lag = AR_lag)

sim = MSTSWG_simulation(dates_sim = dates, dates_original = dates, 
                                data = data, seasons = seasons, names = names, 
                                names_weather_types = names_weather_types, parm = swg,
                                AR_lag = AR_lag, bk = bk)
```

